import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../layouts/backOffice";
import ListAnneeExercice from "../components/anneeExercice";
import useBasePath from "../hooks/useBasePath";

const Home: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>MV - Comptabilité - Accueil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <ListAnneeExercice />
      </Container>
    </BackOfficeLayout>
  );
};

export default Home;
